11470
oracle-livelabs/oci-migration pull request #57
Opened 2024-01-10 09:50 UTC by ecchol

# 11470

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Y] All filenames are lower case (including folders, images, files, etc.)
- [Y] Filenames are descriptive
- [Y] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [Y] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [N] Image references in markdown contain an alternate text

2024-01-11 20:44 UTC, hope-fisher commented
Hi team,

All namez in the folder structure need to be in lowercase. Please update **Troubleshooting** and all references to it (as in the manifest). All other changes look fine, so please ping me when this is done so I can review/approve.

2024-01-12 05:35 UTC, ecchol commented
> Hi team,
> 
> All namez in the folder structure need to be in lowercase. Please update **Troubleshooting** and all references to it (as in the manifest). All other changes look fine, so please ping me when this is done so I can review/approve.

2024-01-12 18:50 UTC, hope-fisher commented
Hi Rahul, I see you've updated the reference to the troubleshooting filepaths, but the folder itself is still uppercase. Can you push your final commit to update that?
![Screenshot 2024-01-12 at 10 48 52 AM](https://github.com/oracle-livelabs/oci-migration/assets/127253314/bf0eb5d3-5b46-4c18-9776-4d403aa1e07c)

2024-01-16 17:40 UTC, ramumg requested changes

2024-01-16 17:40 UTC, ramumg commented on ecc-developer-hol/query/useeccdashboards/useeccdashboards.md
Please make sure all images are displayed. It looks like ecc.png and val1.png are not being displayed properly.

2024-01-18 17:24 UTC, ramumg commented
Hi @ecchol, I wanted to follow up with you about this request.

2024-01-18 19:35 UTC, ramumg submitted a review, later dismissed

2024-01-18 19:35 UTC, ramumg commented on ecc-developer-hol/query/Troubleshooting/start-stop-ecc.md
> +##
This shouldn't be here.

2024-01-18 19:37 UTC, ramumg approved these changes

2024-01-18 19:42 UTC, merged